# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'News' do
  use_frameworks!

  pod 'Kingfisher', '~> 5.0'
  pod 'DateToolsSwift', '~> 4.0'

  target 'NewsTests' do
    inherit! :search_paths
  end

  target 'NewsUITests' do
    inherit! :search_paths
  end

end
